### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by syntaxer** [twskj/FireFoxExt-JSON-In-Place#1]
I have a page that displays a status message which is in JSON format. I use your extension to format the JSON which does a good job, but I have one issue: 
The page aligns the status message to center and the formatted JSON also gets aligned to center.  

Here's what I'm talking about:
![image](https://user-images.githubusercontent.com/5112222/66581972-b28ad280-eb89-11e9-9014-50ecd78e5681.png)

Can you perhaps force the alignment to left?

**Comment by twskj** [comment]
yeah, I'll look into this.
Can you quickly check if the parent has css `text-align: center;`?

**Comment by twskj** [comment]
rolled out on 0.1.4
